import 'package:tencent_cloud_chat_common/components/components_definition/tencent_cloud_chat_component_builder.dart';

class TencentCloudChatSearchBuilders extends TencentCloudChatComponentBuilder {

}