/* Generated by ffmpeg configure */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H

#if defined(FFMPEG_AV_HAVE_BIGENDIAN)
#define AV_HAVE_BIGENDIAN 1
#else
#define AV_HAVE_BIGENDIAN 0
#endif

#if defined(FFMPEG_AV_HAVE_FAST_UNALIGNED)
#define AV_HAVE_FAST_UNALIGNED 1
#else
#define AV_HAVE_FAST_UNALIGNED 0
#endif
#endif /* AVUTIL_AVCONFIG_H */
